#!/bin/bash
count=10
if [ 10 -ne 1 ]
then
	echo "yess 10 is equal to 10"
else
	echo "Yes 10 has never been equal to one unles thy are in defferent bases!"
fi



if [ $count -gt 2 ]
then
	echo "count is greater than 2"
else
	echo "ooh math has a problem"
fi

cat << docs
________________________________________
**these two conditions evaluate if      |
a number is greater than or equal t     |
and these are the ones that we will use |
to build on in the future               |
lets try**                              | 
________________________________________|
docs