#!/bin/bash
cat << the_docs
_____________________________________________________________________
THIS SOFTWARE IS SOLELY AND ONLY FOR PEOPLE WHO ARE LEGIBLE
THIS MEANS PEOPLE WHO HAVE PURCHASED A PRODUCT KEY AND HAVE PAID A PRICE
FIND THE PPRODUCT KEY AT AKA.MS 
IN THE FORMAT OF ***AS8**A***43234

~~~~~~~~~~~~~~~~~_________________~~~~~~~________________________~~_____
THE_DOCS
