#!/bin/bash
cat << heredoc
************************************--*************************************************
this are the steps to follow if you want to use my software
1. read the TC
2. Acccept them
3. INput the product-key
4. Download
**************************************--*********************************************
heredoc
